/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The Reed API
 * The Reed API description
 * OpenAPI spec version: 1.0
 */
import { fetchInstance } from './fetch';
export const appControllerGetHello = (
    
 ) => {
      return fetchInstance<null>(
      {url: `/`, method: 'GET'
    },
      );
    }
  
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
